on:
  workflow_dispatch:
  push:
    branches:
      - main

name: approval

jobs:
  plan:
    name: Plan
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - runs: echo planned

  apply:
    name: Deploy
    needs: plan
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4
      - runs: echo deployed
