on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Deploy infra

jobs:
  run-terraform:
    name: Run Terraform
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          service_account: gha-runner@nitrado-b2b-shared.iam.gserviceaccount.com
          workload_identity_provider: projects/746635298927/locations/global/workloadIdentityPools/github-actions/providers/github-actions

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - id: plan
        run: terraform plan
